package com.mycompany.aplicacionesswing;

import java.text.DecimalFormat;

/**
 *
 * @author JoseLuisDommarcoBerr
 */
public class Calculadora extends javax.swing.JFrame {

    float num1;
    float num2;
    String signo;
    int num3;
    private float igual;
    
    private float igual(float num1, float num2, String signo, int num3) {

        switch (signo) {

            case "+":
                igual = num1 + num2;
                break;

            case "-":
                igual = num1 - num2;
                break;

            case "/":
                igual = num1 / num2;
                break;

            case "*":
                igual = num1 * num2;
                break;

            case "√":
                igual= (float)Math.sqrt(num3);
                break;
            
            case "%":
                igual = num1 % num2;
                break;

        }

        
        
        return igual;
    }
    
    

    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jResultado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtnBorrar = new javax.swing.JButton();
        jBtnRaiz = new javax.swing.JButton();
        jBtnResta = new javax.swing.JButton();
        jBtnPorcentaje = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnDivision = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnMultiplicacion = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnSuma = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnComa = new javax.swing.JButton();
        jBtnIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jResultado.setMinimumSize(new java.awt.Dimension(70, 70));
        jResultado.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jResultado, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(6, 3, 5, 5));

        jBtnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnBorrar.setText("CE");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBorrar);

        jBtnRaiz.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnRaiz.setText("√");
        jBtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRaizActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRaiz);

        jBtnResta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnResta.setText("-");
        jBtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnResta);

        jBtnPorcentaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnPorcentaje.setText("%");
        jBtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPorcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnPorcentaje);

        jBtn7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn7);

        jBtn8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn8);

        jBtn9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn9);

        jBtnDivision.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnDivision.setText("÷");
        jBtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDivision);

        jBtn4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.setToolTipText("");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn4);

        jBtn5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn5);

        jBtn6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn6);

        jBtnMultiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnMultiplicacion.setText("x");
        jBtnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMultiplicacion);

        jBtn1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn1);

        jBtn2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn2);

        jBtn3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn3);

        jBtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnSuma.setText("+");
        jBtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSuma);

        BotonIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BotonIgual.setText("+/-");
        jPanel1.add(BotonIgual);

        jBtn0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn0);

        jBtnComa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnComa.setText(",");
        jBtnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnComa);

        jBtnIgual.setBackground(new java.awt.Color(51, 204, 255));
        jBtnIgual.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBtnIgual.setText("=");
        jBtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnIgual);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        jResultado.setText(jResultado.getText() + "2");

    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed

        jResultado.setText(jResultado.getText() + "3");

    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumaActionPerformed

        num1 = Float.parseFloat(jResultado.getText());
        signo = "+";
        jResultado.setText(" ");

    }//GEN-LAST:event_jBtnSumaActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        
          jResultado.setText(" ");
        
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed

        jResultado.setText(jResultado.getText() + "7");

    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRaizActionPerformed
        
        num3 = Integer.parseInt(jResultado.getText()); 
        signo = "√";
        igual(num1, num2, signo, num3);
        DecimalFormat formato = new DecimalFormat("#.##");
        String valor = String.valueOf(formato.format(igual));
        jResultado.setText(valor);
        
    }//GEN-LAST:event_jBtnRaizActionPerformed

    private void jBtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPorcentajeActionPerformed
         num1 = Float.parseFloat(jResultado.getText());
        signo = "%";
        jResultado.setText(" ");
        
    }//GEN-LAST:event_jBtnPorcentajeActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed

        jResultado.setText(jResultado.getText() + "9");

    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed

        jResultado.setText(jResultado.getText() + "4");

    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed

        jResultado.setText(jResultado.getText() + "6");

    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed

        jResultado.setText(jResultado.getText() + "0");

    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed

        jResultado.setText(jResultado.getText() + "1");

    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed

        jResultado.setText(jResultado.getText() + "5");

    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed

        jResultado.setText(jResultado.getText() + "8");

    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestaActionPerformed

        num1 = Float.parseFloat(jResultado.getText());
        signo = "-";
        jResultado.setText(" ");

    }//GEN-LAST:event_jBtnRestaActionPerformed

    private void jBtnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplicacionActionPerformed
        
        num1 = Float.parseFloat(jResultado.getText());
        signo = "*";
        jResultado.setText(" ");

    }//GEN-LAST:event_jBtnMultiplicacionActionPerformed

    private void jBtnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComaActionPerformed
      
        jResultado.setText(jResultado.getText() + ".");

        
    }//GEN-LAST:event_jBtnComaActionPerformed

    private void jBtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIgualActionPerformed

        num2 = Float.parseFloat(jResultado.getText());
        igual(num1, num2, signo, num3);
        DecimalFormat formato = new DecimalFormat("#.##");
        String valor = String.valueOf(formato.format(igual));
        jResultado.setText(valor);
        
    }//GEN-LAST:event_jBtnIgualActionPerformed

    private void jBtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivisionActionPerformed
        
        num1 = Float.parseFloat(jResultado.getText());
        signo = "/";
        jResultado.setText(" ");
        
    }//GEN-LAST:event_jBtnDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnComa;
    private javax.swing.JButton jBtnDivision;
    private javax.swing.JButton jBtnIgual;
    private javax.swing.JButton jBtnMultiplicacion;
    private javax.swing.JButton jBtnPorcentaje;
    private javax.swing.JButton jBtnRaiz;
    private javax.swing.JButton jBtnResta;
    private javax.swing.JButton jBtnSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jResultado;
    // End of variables declaration//GEN-END:variables
}
